// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaajtljonhgfscovuggx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphYWp0bGpvbmhnZnNjb3Z1Z2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTk0MDgsImV4cCI6MjA2NTQ3NTQwOH0.8k0Pxtsl6QesypiCesuHRoAHWCuhUulV_oIUN1eDc84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);